Release
frontend-park-mail-ru/2017_2_spaceInvasion pull request #9
Opened 2017-09-29 14:25 UTC by Nikita-Boyarskikh

2017-10-27 14:57 UTC, utrobin approved these changes

2017-12-18 10:15 UTC, utrobin commented on public/blocks/form/index.ts
> +    for (let i = 0; i < arr.length; i += 1) {
forEach

2017-12-18 10:16 UTC, utrobin commented on public/blocks/form/index.ts
> +        for (let i = 0; i < elements.length; i += 1) {
forEach

2017-12-18 13:42 UTC, ostapenko-me requested changes
Необходимо **обязательно** удалить из репозитория все исходники `semantic-ui`! Он ставится при установке всех зависимостей из npm'а

2017-12-22 14:50 UTC, merged